apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-demo-7
  labels:
  labels:
    app: "go-demo-7"
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: go-demo-7
          servicePort: 8080
    host: go-demo-7.acme.com
